# Generated by Django 4.2.3 on 2023-09-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('mail', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=2400)),
            ],
        ),
    ]
